name: WolfcareSyncManager
options:
  bundleIdPrefix: com.wolfcare
  deploymentTarget:
    macOS: "13.0"
  createIntermediateGroups: true
configs:
  Debug: debug
  Release: release
targets:
  WolfcareSyncManager:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.wolfcare.SyncManager
        PRODUCT_NAME: "Imitor Sync Manager"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "36"
        SWIFT_VERSION: "5.0"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        ENABLE_HARDENED_RUNTIME: YES
        COMBINE_HIDPI_IMAGES: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SUPPORTS_MACCATALYST: NO
    info:
      path: Sources/App/Info.plist
      properties:
        LSApplicationCategoryType: public.app-category.utilities
        LSMinimumSystemVersion: "13.0"
        LSUIElement: NO
        NSHumanReadableCopyright: "Script written by Santo Berlin © 2026. GUI written by Wolfcare © 2026."
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "36"
        NSPrincipalClass: NSApplication
    scheme:
      testTargets: []
      gatherCoverageData: false
